dependencies:
  - name: minio
    version: 1.3.4
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: nginx-ingress
    version: 0.21.0
    repository: https://kubernetes-charts.storage.googleapis.com/